// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDh_8gL3mpsF_nG9jDyVs35KCqR6pB3BWg',
    appId: '1:18178733946:web:7c86fa15e2f2ee426b88c3',
    messagingSenderId: '18178733946',
    projectId: 'medical-bot-6cfa2',
    authDomain: 'medical-bot-6cfa2.firebaseapp.com',
    databaseURL: 'https://medical-bot-6cfa2-default-rtdb.firebaseio.com',
    storageBucket: 'medical-bot-6cfa2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_naonnFRi-Nu7yYPPTxYy0-ffQNAAMqo',
    appId: '1:18178733946:android:a6a9efa8604e1a766b88c3',
    messagingSenderId: '18178733946',
    projectId: 'medical-bot-6cfa2',
    databaseURL: 'https://medical-bot-6cfa2-default-rtdb.firebaseio.com',
    storageBucket: 'medical-bot-6cfa2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpzZu7lJ5FswsL0orZz_syOWw1klyoDZQ',
    appId: '1:18178733946:ios:ba9c991c219129ac6b88c3',
    messagingSenderId: '18178733946',
    projectId: 'medical-bot-6cfa2',
    databaseURL: 'https://medical-bot-6cfa2-default-rtdb.firebaseio.com',
    storageBucket: 'medical-bot-6cfa2.appspot.com',
    iosBundleId: 'com.example.mineControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpzZu7lJ5FswsL0orZz_syOWw1klyoDZQ',
    appId: '1:18178733946:ios:129c8a8d381edcbf6b88c3',
    messagingSenderId: '18178733946',
    projectId: 'medical-bot-6cfa2',
    databaseURL: 'https://medical-bot-6cfa2-default-rtdb.firebaseio.com',
    storageBucket: 'medical-bot-6cfa2.appspot.com',
    iosBundleId: 'com.example.mineControl.RunnerTests',
  );
}
